[env]
TERM = "screen-256color"

[font]
size = 18

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Regular"

[font.italic]
family = "JetBrains Mono"
style = "Regular"

[font.bold_italic]
family = "JetBrains Mono"
style = "Regular"

[window]
opacity = 0.6
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[general]
import = ["themes/bloodmoon.toml"]
